import { User } from 'lucide-react'
import { Avatar } from '@/presentation/components/ui/avatar'
import { useTranslation } from 'react-i18next'

export function UserProfile({ fingerprint }: { fingerprint: string }) {
  const { t } = useTranslation()
  return (
    <div className="flex items-center space-x-4">
      <Avatar>
        <User size={24} />
      </Avatar>
      <div>
        <h2 className="text-xl font-semibold">
          {t('profile.user', { fingerprint: fingerprint.slice(0, 8) })}
        </h2>
        <p className="text-text-foreground text-xs">
          {t('profile.generated', 'Profile generated by browser fingerprint')}
        </p>
      </div>
    </div>
  )
}
