name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests with coverage
        run: npx vitest run --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true

      - name: Test report 
        run: npx vitest --reporter=junit --outputFile=test-report.junit.xml

      - name: Upload test report to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: SonarQube Scan
        run: echo "Disabling Sonar for Private Repo, Re enabling when ready."
        # uses: sonarsource/sonarqube-scan-action@v2.0.2
        # with:
        #   projectBaseDir: .
        # env:
        #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        #   SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: OWASP Dependency-Check
        run: echo "OWASP Dependency-Check would run here. Configure with the dependency-check-action or CLI."
